import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // ---------------------------------------------------------------------------
  // The DAL guard.
  //
  // Payload's Local API defaults `overrideAccess` to TRUE, so a bare
  // `payload.find()` in a server component runs with access control switched off
  // and no user attached — every `access` function on every collection is
  // silently bypassed. It fails open, which is the worst possible default for a
  // multi-owner billing app.
  //
  // So nothing under src/app/(app) may reach Payload directly. Everything goes
  // through src/lib/auth/dal.ts, which always passes `overrideAccess: false` and
  // a resolved user. The two places that genuinely need unscoped access (the
  // public invoice portal and background jobs) get named escape hatches in the
  // DAL, so this rule needs no exceptions.
  // ---------------------------------------------------------------------------
  {
    files: ["src/app/(app)/**/*.{ts,tsx}"],
    rules: {
      // NOTE: this rule takes a flat list of path objects, and `allowTypeImports`
      // belongs on each entry — not wrapped in a `{ paths: [...] }` object with
      // `allowTypeImports` hoisted to the root. The wrapped form is accepted by
      // the base ESLint rule but rejected by the typescript-eslint one, and the
      // whole config fails to load rather than the rule quietly doing nothing.
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          name: "payload",
          importNames: ["getPayload"],
          allowTypeImports: true,
          message:
            "Do not call getPayload() from (app). Payload's Local API defaults overrideAccess to true, which bypasses all access control. Use the helpers in @/lib/auth/dal instead.",
        },
        {
          name: "@payload-config",
          allowTypeImports: true,
          message:
            "Do not import the Payload config from (app). Use the helpers in @/lib/auth/dal instead.",
        },
      ],
    },
  },

  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Payload-generated — never hand-edited, never linted:
    "src/payload-types.ts",
    "src/payload-generated-schema.ts",
    "src/app/(payload)/admin/importMap.js",
    // Generated by `payload migrate:create` — never hand-edited.
    "src/migrations/**",
  ]),
]);

export default eslintConfig;
