/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    clients: Client;
    invoices: Invoice;
    'bank-accounts': BankAccount;
    media: Media;
    'number-sequences': NumberSequence;
    'activity-log': ActivityLog;
    services: Service;
    'service-billings': ServiceBilling;
    quotes: Quote;
    payments: Payment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'bank-accounts': BankAccountsSelect<false> | BankAccountsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'number-sequences': NumberSequencesSelect<false> | NumberSequencesSelect<true>;
    'activity-log': ActivityLogSelect<false> | ActivityLogSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-billings': ServiceBillingsSelect<false> | ServiceBillingsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'business-settings': BusinessSetting;
    'invoice-defaults': InvoiceDefault;
  };
  globalsSelect: {
    'business-settings': BusinessSettingsSelect<false> | BusinessSettingsSelect<true>;
    'invoice-defaults': InvoiceDefaultsSelect<false> | InvoiceDefaultsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'user' | 'admin';
  /**
   * Drives due-date arithmetic and the daily reminder sweep. A "day only" invoice date must never shift across a UTC boundary.
   */
  timezone: 'Australia/Melbourne' | 'Australia/Sydney' | 'Australia/Brisbane' | 'Australia/Perth' | 'Pacific/Auckland';
  locale: 'en-AU' | 'en-NZ';
  notificationPrefs?: {
    emailOnInvoicePaid?: boolean | null;
    emailOnInvoiceViewed?: boolean | null;
    emailOnQuoteAccepted?: boolean | null;
    dailyReadyToBillDigest?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  owner?: (number | null) | User;
  /**
   * Exactly as it should appear in the BILL TO block.
   */
  name: string;
  /**
   * Optional. Stored digits-only, printed grouped.
   */
  abn?: string | null;
  /**
   * Primary billing contact. Invoices and reminders go here.
   */
  email?: string | null;
  contacts?:
    | {
        name: string;
        email?: string | null;
        phone?: string | null;
        /**
         * e.g. Accounts payable
         */
        role?: string | null;
        /**
         * Copy this person on invoice and reminder emails.
         */
        ccOnInvoices?: boolean | null;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postcode?: string | null;
    country?: string | null;
  };
  defaultCurrency: 'AUD' | 'NZD' | 'USD' | 'PHP';
  /**
   * Invoices commonly print "Due: On Receipt" in the header while the terms text states a number of days. This field is what the header prints; paymentTermsDays is what the terms text says.
   */
  defaultDueMode: 'on_receipt' | 'net_days' | 'fixed_date';
  /**
   * Per-client, because payment terms genuinely differ between clients.
   */
  defaultPaymentTermsDays?: number | null;
  /**
   * Fixed-fee work reads "Qty"; time-based work reads "Hours".
   */
  defaultQtyLabel: 'Qty' | 'Hours' | 'Days' | 'Units';
  /**
   * Used when generating invoice lines from tracked time.
   */
  defaultHourlyRateCents?: number | null;
  status: 'active' | 'archived';
  tags?: string[] | null;
  /**
   * Internal only. Never printed on an invoice.
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  owner?: (number | null) | User;
  /**
   * Allocated atomically on the first transition to Sent, so drafts never burn a number and the ATO-visible sequence has no gaps.
   */
  invoiceNumber?: number | null;
  /**
   * The printed form, e.g. "#6" or "INV-006", built from the numbering settings. Stored rather than virtual so it is searchable and sortable — Payload virtual fields are neither in Postgres.
   */
  displayNumber?: string | null;
  status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
  client: number | Client;
  /**
   * Optional subject line, e.g. "Hosting — August 2026".
   */
  title?: string | null;
  /**
   * The client's PO or job reference, if they use one.
   */
  reference?: string | null;
  issuedDate: string;
  /**
   * What the "Due:" line prints.
   */
  dueMode: 'on_receipt' | 'net_days' | 'fixed_date';
  /**
   * Drives the terms text and the reminder schedule.
   */
  paymentTermsDays?: number | null;
  /**
   * Derived from the issue date and the due mode. Reminders key off this.
   */
  dueDate?: string | null;
  currency: 'AUD' | 'NZD' | 'USD' | 'PHP';
  /**
   * Column header for the quantity column on the PDF.
   */
  qtyLabel: 'Qty' | 'Hours' | 'Days' | 'Units';
  /**
   * Editable only while the invoice is a draft.
   */
  lineItems: {
    description: string;
    quantityMilli: number;
    /**
     * Optional, e.g. "hours", "days", "each".
     */
    unit?: string | null;
    unitPriceCents: number;
    /**
     * Rounded once, here. The subtotal is the plain sum of these.
     */
    lineTotalCents?: number | null;
    id?: string | null;
  }[];
  /**
   * Applied before tax.
   */
  discountCents?: number | null;
  /**
   * Basis points: 1000 = 10% (AU GST), 1500 = 15% (NZ GST). Stays 0 while not GST-registered.
   */
  taxRateBasisPoints: number;
  /**
   * Only printed when the rate is above zero.
   */
  taxLabel?: string | null;
  /**
   * Frozen copy of the GST registration flag at issue time, so a future registration never retroactively relabels an old invoice as a TAX INVOICE.
   */
  gstRegisteredAtIssue?: boolean | null;
  subtotalCents?: number | null;
  taxCents?: number | null;
  totalCents?: number | null;
  amountPaidCents?: number | null;
  balanceCents?: number | null;
  /**
   * Printed under the totals, above the terms.
   */
  notes?: string | null;
  /**
   * Seeded from the default template in Invoice defaults, then editable per invoice.
   */
  terms?: string | null;
  /**
   * Defaults to the default account for this invoice currency.
   */
  bankAccount?: (number | null) | BankAccount;
  /**
   * Frozen when the invoice is sent. Renaming a client in 2027 must not rewrite a 2026 document.
   */
  billToSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Frozen business details, including the bank account actually quoted.
   */
  payableToSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The exact PDF the client received. Immutable once sent.
   */
  archivedPdf?: (number | null) | Media;
  /**
   * Opaque, revocable. Grants read of this one invoice via /i/[token].
   */
  shareToken?: string | null;
  sentAt?: string | null;
  viewedAt?: string | null;
  paidAt?: string | null;
  sourceQuote?: (number | null) | Quote;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-accounts".
 */
export interface BankAccount {
  id: number;
  owner?: (number | null) | User;
  /**
   * Internal name, e.g. "Everyday (AUD)" or "ASB (NZD)".
   */
  label: string;
  /**
   * Invoices in this currency default to this account.
   */
  currency: 'AUD' | 'NZD' | 'USD' | 'PHP';
  accountName?: string | null;
  bankName?: string | null;
  /**
   * Australian accounts only. Six digits, e.g. 123456.
   */
  bsb?: string | null;
  /**
   * AU: the account number alone. NZ: the full grouped form, e.g. 00-0000-0000000-00.
   */
  accountNumber: string;
  /**
   * Only needed for international transfers.
   */
  swift?: string | null;
  iban?: string | null;
  /**
   * The account preselected for new invoices in this currency.
   */
  isDefault?: boolean | null;
  /**
   * Hidden from new invoices. Existing invoices keep their frozen snapshot, so archiving never rewrites a sent document.
   */
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text, for images used in the app.
   */
  alt?: string | null;
  /**
   * Archived invoice PDFs are immutable once the invoice is sent — they are the record of what the client actually received.
   */
  kind?: ('general' | 'logo' | 'invoice-pdf' | 'quote-pdf' | 'attachment') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  owner?: (number | null) | User;
  quoteNumber?: number | null;
  status: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired' | 'cancelled';
  client: number | Client;
  title: string;
  reference?: string | null;
  serviceSummary?: string | null;
  scopeBullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  issuedDate: string;
  validUntil: string;
  currency: 'AUD' | 'NZD' | 'USD' | 'PHP';
  lineItems?:
    | {
        description: string;
        quantityMilli: number;
        unitPriceCents: number;
        lineTotalCents?: number | null;
        id?: string | null;
      }[]
    | null;
  taxRateBasisPoints: number;
  subtotalCents?: number | null;
  taxCents?: number | null;
  totalCents?: number | null;
  terms?: string | null;
  /**
   * Typed name captured at acceptance.
   */
  acceptedByName?: string | null;
  acceptedAt?: string | null;
  shareToken?: string | null;
  /**
   * Set once, on conversion. The predecessor dropped terms, summary, scope and reference during conversion and clobbered the notes — this link exists so nothing is lost.
   */
  convertedToInvoice?: (number | null) | Invoice;
  updatedAt: string;
  createdAt: string;
}
/**
 * Invoice and quote counters. Seed these to continue an existing numbering series.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "number-sequences".
 */
export interface NumberSequence {
  id: number;
  owner?: (number | null) | User;
  kind: 'invoice' | 'quote';
  /**
   * The last number handed out. The next allocation returns lastValue + 1.
   */
  lastValue: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only. Records every status transition, including forced ones.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log".
 */
export interface ActivityLog {
  id: number;
  owner?: (number | null) | User;
  /**
   * Human-readable one-liner for the admin list view.
   */
  summary?: string | null;
  entityType: 'invoice' | 'quote';
  entityId: string;
  entityNumber?: number | null;
  fromStatus: string;
  toStatus: string;
  /**
   * True when the transition skipped the state machine. A reason is mandatory in that case.
   */
  isAdminOverride?: boolean | null;
  reason?: string | null;
  actor?: (number | null) | User;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Monthly hosting and maintenance. The billing run raises a draft invoice for each period that has started.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  owner?: (number | null) | User;
  /**
   * Internal name, e.g. "Hosting — example.com".
   */
  name: string;
  client: number | Client;
  kind: 'hosting' | 'maintenance' | 'domain' | 'ssl' | 'retainer' | 'other';
  /**
   * The site this covers, if applicable. Handy for renewal reminders.
   */
  domain?: string | null;
  /**
   * Only Active services are billed. Paused keeps the history without invoicing.
   */
  status: 'active' | 'paused' | 'cancelled';
  currency: 'AUD' | 'NZD' | 'USD' | 'PHP';
  /**
   * What the client pays each period.
   */
  chargeCents: number;
  billingPeriod: 'monthly' | 'quarterly' | 'annually';
  /**
   * The billing anchor. Every future date is measured from here, so a service starting on the 31st keeps billing on the 31st instead of drifting back after February.
   */
  startDate: string;
  /**
   * Optional. Billing stops once a period would start after this.
   */
  endDate?: string | null;
  /**
   * How many periods have been invoiced. Advanced by the billing run.
   */
  periodsBilled: number;
  /**
   * Derived from the start date and periods billed. Never edited directly.
   */
  nextInvoiceOn?: string | null;
  /**
   * Include this service in the billing run.
   */
  autoGenerate?: boolean | null;
  /**
   * Off by default, deliberately. Generated invoices land as drafts so you see them before a client does.
   */
  autoSend?: boolean | null;
  /**
   * Defaults to the service name.
   */
  lineDescription?: string | null;
  /**
   * Usually 1 for a flat monthly fee.
   */
  quantityMilli?: number | null;
  qtyLabel?: ('Qty' | 'Hours' | 'Days' | 'Units') | null;
  /**
   * Overrides the client default for invoices from this service.
   */
  paymentTermsDays?: number | null;
  bankAccount?: (number | null) | BankAccount;
  /**
   * What this service costs you — hosting plan, registrar, CDN. Drives the margin figures below, and `Renews on` drives renewal reminders.
   */
  costs?:
    | {
        /**
         * e.g. Vercel, Cloudflare.
         */
        vendor: string;
        description?: string | null;
        amountCents: number;
        /**
         * If this differs from the service currency it is excluded from margin rather than converted at a guessed rate.
         */
        currency: 'AUD' | 'NZD' | 'USD' | 'PHP';
        period: 'one_off' | 'monthly' | 'quarterly' | 'annually';
        /**
         * When this expires. A lapsed domain takes the client’s site down, so this is the field that earns its keep.
         */
        renewsOn?: string | null;
        /**
         * How far ahead to warn you. 0 disables the reminder.
         */
        notifyDaysBefore?: number | null;
        id?: string | null;
      }[]
    | null;
  monthlyChargeCents?: number | null;
  monthlyCostCents?: number | null;
  monthlyMarginCents?: number | null;
  /**
   * Set when a cost is in another currency. Those costs are left out of margin instead of being converted at a rate nobody recorded.
   */
  costCurrencyMismatch?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only record of which service periods have been invoiced.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-billings".
 */
export interface ServiceBilling {
  id: number;
  owner?: (number | null) | User;
  service: number | Service;
  invoice?: (number | null) | Invoice;
  periodStart: string;
  periodEnd: string;
  /**
   * Human-readable period, for the list view.
   */
  periodLabel?: string | null;
  chargeCents?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  owner?: (number | null) | User;
  invoice: number | Invoice;
  amountCents: number;
  receivedOn: string;
  method: 'bank_transfer' | 'card' | 'cash' | 'other';
  /**
   * Bank reference or receipt number.
   */
  reference?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'bank-accounts';
        value: number | BankAccount;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'number-sequences';
        value: number | NumberSequence;
      } | null)
    | ({
        relationTo: 'activity-log';
        value: number | ActivityLog;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-billings';
        value: number | ServiceBilling;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  timezone?: T;
  locale?: T;
  notificationPrefs?:
    | T
    | {
        emailOnInvoicePaid?: T;
        emailOnInvoiceViewed?: T;
        emailOnQuoteAccepted?: T;
        dailyReadyToBillDigest?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  owner?: T;
  name?: T;
  abn?: T;
  email?: T;
  contacts?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        role?: T;
        ccOnInvoices?: T;
        id?: T;
      };
  phone?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postcode?: T;
        country?: T;
      };
  defaultCurrency?: T;
  defaultDueMode?: T;
  defaultPaymentTermsDays?: T;
  defaultQtyLabel?: T;
  defaultHourlyRateCents?: T;
  status?: T;
  tags?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  owner?: T;
  invoiceNumber?: T;
  displayNumber?: T;
  status?: T;
  client?: T;
  title?: T;
  reference?: T;
  issuedDate?: T;
  dueMode?: T;
  paymentTermsDays?: T;
  dueDate?: T;
  currency?: T;
  qtyLabel?: T;
  lineItems?:
    | T
    | {
        description?: T;
        quantityMilli?: T;
        unit?: T;
        unitPriceCents?: T;
        lineTotalCents?: T;
        id?: T;
      };
  discountCents?: T;
  taxRateBasisPoints?: T;
  taxLabel?: T;
  gstRegisteredAtIssue?: T;
  subtotalCents?: T;
  taxCents?: T;
  totalCents?: T;
  amountPaidCents?: T;
  balanceCents?: T;
  notes?: T;
  terms?: T;
  bankAccount?: T;
  billToSnapshot?: T;
  payableToSnapshot?: T;
  archivedPdf?: T;
  shareToken?: T;
  sentAt?: T;
  viewedAt?: T;
  paidAt?: T;
  sourceQuote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-accounts_select".
 */
export interface BankAccountsSelect<T extends boolean = true> {
  owner?: T;
  label?: T;
  currency?: T;
  accountName?: T;
  bankName?: T;
  bsb?: T;
  accountNumber?: T;
  swift?: T;
  iban?: T;
  isDefault?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "number-sequences_select".
 */
export interface NumberSequencesSelect<T extends boolean = true> {
  owner?: T;
  kind?: T;
  lastValue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log_select".
 */
export interface ActivityLogSelect<T extends boolean = true> {
  owner?: T;
  summary?: T;
  entityType?: T;
  entityId?: T;
  entityNumber?: T;
  fromStatus?: T;
  toStatus?: T;
  isAdminOverride?: T;
  reason?: T;
  actor?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  owner?: T;
  name?: T;
  client?: T;
  kind?: T;
  domain?: T;
  status?: T;
  currency?: T;
  chargeCents?: T;
  billingPeriod?: T;
  startDate?: T;
  endDate?: T;
  periodsBilled?: T;
  nextInvoiceOn?: T;
  autoGenerate?: T;
  autoSend?: T;
  lineDescription?: T;
  quantityMilli?: T;
  qtyLabel?: T;
  paymentTermsDays?: T;
  bankAccount?: T;
  costs?:
    | T
    | {
        vendor?: T;
        description?: T;
        amountCents?: T;
        currency?: T;
        period?: T;
        renewsOn?: T;
        notifyDaysBefore?: T;
        id?: T;
      };
  monthlyChargeCents?: T;
  monthlyCostCents?: T;
  monthlyMarginCents?: T;
  costCurrencyMismatch?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-billings_select".
 */
export interface ServiceBillingsSelect<T extends boolean = true> {
  owner?: T;
  service?: T;
  invoice?: T;
  periodStart?: T;
  periodEnd?: T;
  periodLabel?: T;
  chargeCents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  owner?: T;
  quoteNumber?: T;
  status?: T;
  client?: T;
  title?: T;
  reference?: T;
  serviceSummary?: T;
  scopeBullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  issuedDate?: T;
  validUntil?: T;
  currency?: T;
  lineItems?:
    | T
    | {
        description?: T;
        quantityMilli?: T;
        unitPriceCents?: T;
        lineTotalCents?: T;
        id?: T;
      };
  taxRateBasisPoints?: T;
  subtotalCents?: T;
  taxCents?: T;
  totalCents?: T;
  terms?: T;
  acceptedByName?: T;
  acceptedAt?: T;
  shareToken?: T;
  convertedToInvoice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  owner?: T;
  invoice?: T;
  amountCents?: T;
  receivedOn?: T;
  method?: T;
  reference?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-settings".
 */
export interface BusinessSetting {
  id: number;
  tradingName: string;
  /**
   * Only if it differs from the trading name.
   */
  legalName?: string | null;
  /**
   * Stored digits-only, printed grouped — e.g. 51 824 753 556.
   */
  abn: string;
  email: string;
  phone?: string | null;
  website?: string | null;
  logo?: (number | null) | Media;
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postcode?: string | null;
    country?: string | null;
  };
  /**
   * Turn on once turnover reaches A$75,000 (NZ$60,000). This single flag flips the document title from INVOICE to TAX INVOICE, adds the tax row, and sets the rate.
   */
  gstRegistered?: boolean | null;
  /**
   * Invoices issued before this date keep saying INVOICE, so registering never retroactively relabels old documents.
   */
  gstRegisteredFrom?: string | null;
  taxJurisdiction: 'AU' | 'NZ';
  /**
   * Only ever printed when the rate is above zero.
   */
  taxLabel?: string | null;
  /**
   * Allocating on send means abandoned drafts never consume a number, so the issued sequence has no gaps.
   */
  numberAllocationMode: 'onSend' | 'onCreate';
  /**
   * Optional, e.g. "INV-". Leave empty for a bare number.
   */
  numberPrefix?: string | null;
  /**
   * 0 prints "6"; 3 prints "006".
   */
  numberPadding?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-defaults".
 */
export interface InvoiceDefault {
  id: number;
  /**
   * Order, labels and widths of the items table. Ratios are relative — the predecessor used 5:2:2:2.
   */
  columnLayout: {
    key: 'description' | 'quantity' | 'unitPrice' | 'lineTotal';
    /**
     * Printed header. The quantity column is overridden per invoice.
     */
    label: string;
    ratio: number;
    align: 'left' | 'right';
    id?: string | null;
  }[];
  /**
   * Full grid borders and a shaded body row, matching a typical hand-made invoice template.
   */
  tableStyle?: {
    gridBorders?: boolean | null;
    shadeBodyRows?: boolean | null;
    boldDescription?: boolean | null;
  };
  /**
   * With no GST the subtotal equals the total, so printing both is noise — go straight to AMOUNT DUE.
   */
  showSubtotalWhenUntaxed?: boolean | null;
  /**
   * Must resolve to exactly one place or the details print twice. Keep this consistent with the wording of the terms template — if the terms say "the account listed above", the details belong in PAYABLE TO.
   */
  bankDetailsPlacement: 'terms' | 'payable_to' | 'both';
  /**
   * Copied onto each new invoice and then editable. {{paymentTermsDays}} and {{bankDetails}} are substituted at creation.
   */
  defaultTermsTemplate: string;
  /**
   * Sits in the content flow, left-aligned, after the terms.
   */
  closingLine?: string | null;
  /**
   * Optional centred footer, repeated on every page. Left empty on purpose — the closing line above already thanks the client, so a footer saying the same thing read as duplication. Fill this in only for something different, e.g. a website or ABN reminder.
   */
  footerLine?: string | null;
  /**
   * Phase 2. Negative is before the due date, positive after. Each fires at most once per invoice.
   */
  reminderOffsetsDays?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-settings_select".
 */
export interface BusinessSettingsSelect<T extends boolean = true> {
  tradingName?: T;
  legalName?: T;
  abn?: T;
  email?: T;
  phone?: T;
  website?: T;
  logo?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postcode?: T;
        country?: T;
      };
  gstRegistered?: T;
  gstRegisteredFrom?: T;
  taxJurisdiction?: T;
  taxLabel?: T;
  numberAllocationMode?: T;
  numberPrefix?: T;
  numberPadding?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-defaults_select".
 */
export interface InvoiceDefaultsSelect<T extends boolean = true> {
  columnLayout?:
    | T
    | {
        key?: T;
        label?: T;
        ratio?: T;
        align?: T;
        id?: T;
      };
  tableStyle?:
    | T
    | {
        gridBorders?: T;
        shadeBodyRows?: T;
        boldDescription?: T;
      };
  showSubtotalWhenUntaxed?: T;
  bankDetailsPlacement?: T;
  defaultTermsTemplate?: T;
  closingLine?: T;
  footerLine?: T;
  reminderOffsetsDays?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}